"use client";

export interface OinkashTip {
  cat: 'Hábito' | 'Ahorro' | 'Psicología' | 'Seguridad';
  text: string;
}

export const OINKASH_TIPS: OinkashTip[] = [
  // AHORRO (25)
  { cat: 'Ahorro', text: 'Aplica la regla de las 48 horas: si quieres algo, espera 2 días antes de comprar.' },
  { cat: 'Ahorro', text: 'Preparar café en casa te ahorra hasta $1,200 al mes en promedio.' },
  { cat: 'Ahorro', text: 'Compra marcas genéricas en productos de limpieza; la fórmula suele ser idéntica.' },
  { cat: 'Ahorro', text: 'Cancela esa suscripción que no has usado en los últimos 30 días.' },
  { cat: 'Ahorro', text: 'Revisa la presión de tus llantas; una presión baja gasta más gasolina.' },
  { cat: 'Ahorro', text: 'Compra frutas y verduras de temporada; son más baratas y frescas.' },
  { cat: 'Ahorro', text: 'Desconecta aparatos que no uses; el "consumo vampiro" suma a tu recibo de luz.' },
  { cat: 'Ahorro', text: 'Usa cupones de descuento solo para cosas que ya tenías planeado comprar.' },
  { cat: 'Ahorro', text: 'Compara precios por unidad (litro/kilo) no solo el precio final del empaque.' },
  { cat: 'Ahorro', text: 'Lleva tu propia bolsa al súper; muchos lugares cobran por ellas ahora.' },
  { cat: 'Ahorro', text: 'Automatiza una transferencia de ahorro el mismo día que recibes tu sueldo.' },
  { cat: 'Ahorro', text: 'Antes de tirar algo, mira si se puede reparar. El remiendo ahorra el reemplazo.' },
  { cat: 'Ahorro', text: 'Usa focos LED; consumen hasta un 80% menos energía que los tradicionales.' },
  { cat: 'Ahorro', text: 'Planifica tus comidas de la semana para evitar comprar comida rápida por falta de tiempo.' },
  { cat: 'Ahorro', text: 'Busca programas de lealtad en los lugares que frecuentas de verdad.' },
  { cat: 'Ahorro', text: 'Si sales a comer, comparte el postre; ahorras dinero y calorías.' },
  { cat: 'Ahorro', text: 'Usa el transporte público o camina para trayectos menores a 2 kilómetros.' },
  { cat: 'Ahorro', text: 'Vende lo que no usas en apps de segunda mano; es dinero "atrapado".' },
  { cat: 'Ahorro', text: 'Limpia los filtros de tu aire acondicionado; sucio gasta mucha más energía.' },
  { cat: 'Ahorro', text: 'Llena siempre la lavadora; gastarás menos agua y detergente por carga.' },
  { cat: 'Ahorro', text: 'Usa agua fría para lavar la ropa; el 90% de la energía de la lavadora se va en calentar agua.' },
  { cat: 'Ahorro', text: 'Revisa tus seguros una vez al año para ver si hay mejores precios en el mercado.' },
  { cat: 'Ahorro', text: 'Aprovecha las bibliotecas públicas o intercambia libros en lugar de comprarlos nuevos.' },
  { cat: 'Ahorro', text: 'Usa regaderas de bajo flujo para ahorrar miles de litros de agua al año.' },
  { cat: 'Ahorro', text: 'Lava tu auto tú mismo en lugar de llevarlo al car wash cada semana.' },

  // PSICOLOGÍA (25)
  { cat: 'Psicología', text: 'No ahorres lo que queda después de gastar, gasta lo que queda después de ahorrar.' },
  { cat: 'Psicología', text: 'El marketing está diseñado para que sientas que te falta algo. Respira antes de comprar.' },
  { cat: 'Psicología', text: 'Tu valor como persona no depende de tu saldo bancario ni de lo que posees.' },
  { cat: 'Psicología', text: 'Evita comprar cuando estés triste o muy feliz; las emociones nublan el juicio financiero.' },
  { cat: 'Psicología', text: 'La envidia financiera es cara. No intentes mantener el ritmo de vida de otros.' },
  { cat: 'Psicología', text: 'Visualiza tu meta de ahorro cada vez que sientas el impulso de un gasto hormiga.' },
  { cat: 'Psicología', text: 'El dinero es una herramienta, no el fin último. Úsalo para comprar libertad, no estatus.' },
  { cat: 'Psicología', text: 'Aprende a decir "no está en mi presupuesto por ahora" sin sentir vergüenza.' },
  { cat: 'Psicología', text: 'Date un gusto pequeño planeado; la privación total lleva a atracones de gastos.' },
  { cat: 'Psicología', text: 'Entiende la diferencia entre "necesidad" y "deseo" antes de pasar la tarjeta.' },
  { cat: 'Psicología', text: 'Gastar dinero para impresionar a gente que no te agrada es una trampa sin fin.' },
  { cat: 'Psicología', text: 'La gratificación instantánea es el enemigo número uno de tu riqueza futura.' },
  { cat: 'Psicología', text: 'Escribe tus metas financieras. Lo que no se mide y no se anota, no existe.' },
  { cat: 'Psicología', text: 'Piensa en el precio de algo como "horas de vida trabajadas", no solo en pesos.' },
  { cat: 'Psicología', text: 'El miedo a perderse de algo (FOMO) vacía carteras. Elige tus prioridades.' },
  { cat: 'Psicología', text: 'Perdónate por los errores financieros pasados, pero aprende la lección hoy.' },
  { cat: 'Psicología', text: 'La paz mental de tener un fondo de emergencia no tiene precio de etiqueta.' },
  { cat: 'Psicología', text: 'No uses el "me lo merezco" como excusa para sabotear tu futuro.' },
  { cat: 'Psicología', text: 'El cerebro siente el mismo placer al comprar que al ahorrar si tienes una meta clara.' },
  { cat: 'Psicología', text: 'Simplifica tu vida; menos posesiones significan menos gastos de mantenimiento.' },
  { cat: 'Psicología', text: 'Tu cuenta bancaria es un reflejo de tus prioridades actuales.' },
  { cat: 'Psicología', text: 'Deja de buscar la aprobación de los demás a través de tus compras.' },
  { cat: 'Psicología', text: 'El éxito financiero no es cuánto ganas, sino cuánto conservas.' },
  { cat: 'Psicología', text: 'Comprar cosas no llenará el vacío que deja la falta de propósito.' },
  { cat: 'Psicología', text: 'La paciencia es la habilidad financiera más rentable que puedes desarrollar.' },

  // SEGURIDAD (25)
  { cat: 'Seguridad', text: 'Usa tarjetas digitales con CVV dinámico para todas tus compras en línea.' },
  { cat: 'Seguridad', text: 'Nunca compartas tu NIP o contraseñas por teléfono, ni aunque digan ser del banco.' },
  { cat: 'Seguridad', text: 'Activa la autenticación de dos pasos (2FA) en todas tus apps financieras.' },
  { cat: 'Seguridad', text: 'Revisa tus estados de cuenta cada semana para detectar cargos no reconocidos rápido.' },
  { cat: 'Seguridad', text: 'Evita usar redes WiFi públicas para entrar a tu banca móvil o a Oinkash.' },
  { cat: 'Seguridad', text: 'Si un cajero automático parece manipulado o tiene piezas flojas, no lo uses.' },
  { cat: 'Seguridad', text: 'Cambia tus contraseñas importantes al menos cada 6 meses.' },
  { cat: 'Seguridad', text: 'No guardes fotos de tus tarjetas en la galería de tu celular.' },
  { cat: 'Seguridad', text: 'Desconfía de ofertas que parecen demasiado buenas para ser verdad; suelen ser estafas.' },
  { cat: 'Seguridad', text: 'Bloquea tus tarjetas desde la app cuando no las estés usando.' },
  { cat: 'Seguridad', text: 'Mantén el sistema operativo de tu celular siempre actualizado.' },
  { cat: 'Seguridad', text: 'No hagas clic en enlaces que te lleguen por SMS diciendo que tu cuenta está bloqueada.' },
  { cat: 'Seguridad', text: 'Usa una contraseña diferente para cada cuenta; un gestor de contraseñas ayuda.' },
  { cat: 'Seguridad', text: 'Tritura o destruye documentos que tengan tu nombre y números de cuenta antes de tirarlos.' },
  { cat: 'Seguridad', text: 'Activa las notificaciones de gastos en tiempo real en las apps de tus bancos.' },
  { cat: 'Seguridad', text: 'Si pierdes tu celular, llama de inmediato a tu banco para desvincular el dispositivo.' },
  { cat: 'Seguridad', text: 'Verifica que la URL empiece con "https://" antes de meter tus datos de tarjeta.' },
  { cat: 'Seguridad', text: 'No des permiso de acceso a tus contactos a apps de préstamos dudosos.' },
  { cat: 'Seguridad', text: 'Revisa tu historial crediticio (Buró) una vez al año para detectar robo de identidad.' },
  { cat: 'Seguridad', text: 'Limpia el caché de tu navegador después de hacer trámites bancarios en una PC ajena.' },
  { cat: 'Seguridad', text: 'Nunca uses la misma contraseña para tu correo y para tu banco.' },
  { cat: 'Seguridad', text: 'Desactiva el autocompletado de tarjetas en sitios web que no frecuentas.' },
  { cat: 'Seguridad', text: 'Configura montos máximos diarios de retiro y compra en tus tarjetas.' },
  { cat: 'Seguridad', text: 'Si viajas al extranjero, avisa a tu banco para que no bloqueen tus tarjetas.' },
  { cat: 'Seguridad', text: 'Usa biometría (huella o cara) para desbloquear tus apps bancarias.' },

  // HÁBITO (25)
  { cat: 'Hábito', text: 'Registra tus gastos en el momento que ocurren. La memoria es traicionera, Oinkash no.' },
  { cat: 'Hábito', text: 'Dedica 10 minutos cada domingo a revisar tus finanzas de la semana.' },
  { cat: 'Hábito', text: 'Carga siempre una botella de agua; evitarás comprar una por impulso en la calle.' },
  { cat: 'Hábito', text: 'Antes de dormir, revisa si tienes pagos pendientes para el día siguiente.' },
  { cat: 'Hábito', text: 'Lleva una lista de súper y apégate a ella estrictamente.' },
  { cat: 'Hábito', text: 'Establece un día a la semana como "Día de Cero Gastos".' },
  { cat: 'Hábito', text: 'Limpia tu correo de newsletters de tiendas que solo te incitan a comprar.' },
  { cat: 'Hábito', text: 'Lee al menos un artículo o escucha un podcast de finanzas a la semana.' },
  { cat: 'Hábito', text: 'Revisa tu score de salud financiera en Oinkash todos los días.' },
  { cat: 'Hábito', text: 'Ahorra primero, gasta después. Es el hábito de la gente próspera.' },
  { cat: 'Hábito', text: 'Lleva tus propios snacks al cine o al trabajo.' },
  { cat: 'Hábito', text: 'Si vas a comprar algo caro, búscalo primero en 3 lugares diferentes.' },
  { cat: 'Hábito', text: 'Categoriza tus gastos correctamente para saber a dónde se va realmente tu dinero.' },
  { cat: 'Hábito', text: 'Habla de dinero con tu pareja o familia de forma abierta y tranquila.' },
  { cat: 'Hábito', text: 'Evita ir al súper con hambre; terminarás comprando de más.' },
  { cat: 'Hábito', text: 'Aprende a cocinar un plato nuevo cada mes; te hará menos dependiente de los restaurantes.' },
  { cat: 'Hábito', text: 'Usa efectivo para tus "gastos de diversión"; cuando se acaba el papel, se acabó la fiesta.' },
  { cat: 'Hábito', text: 'Ponle nombre a tus ahorros (ej: "Viaje a Japón"); motiva más que solo un número.' },
  { cat: 'Hábito', text: 'Revisa tus suscripciones activas al inicio de cada mes.' },
  { cat: 'Hábito', text: 'Sé agradecido con lo que ya tienes; la gratitud reduce el deseo de comprar más.' },
  { cat: 'Hábito', text: 'Lleva un registro de los préstamos que haces a amigos; las cuentas claras mantienen amistades.' },
  { cat: 'Hábito', text: 'No uses tu fondo de emergencia para vacaciones; el nombre lo dice: es para EMERGENCIAS.' },
  { cat: 'Hábito', text: 'Dedica tiempo a educarte sobre inversiones básicas.' },
  { cat: 'Hábito', text: 'Pregúntate "¿Esto me servirá en 6 meses?" antes de comprarlo.' },
  { cat: 'Hábito', text: 'Celebra tus pequeñas victorias de ahorro; la motivación es clave.' },
];

export const getRandomTip = (): OinkashTip => {
  const randomIndex = Math.floor(Math.random() * OINKASH_TIPS.length);
  return OINKASH_TIPS[randomIndex];
};