// This file is automatically generated.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nyzquoiwwywbqbhdowau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_ZzJFZMHMVWV5sG_rTUWy3Q__e8SKNaO";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);